apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: valkey-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
        role: cache
        part-of: valkey-demo
        tier: backend
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey-demo
spec:
  selector:
    app: valkey
  ports:
    - port: 6379
      targetPort: 6379
